apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: namespaces-admission-webhook
spec:
  secretName: namespaces-admission-webhook
  issuerRef:
    name: movedigital-ca
    kind: ClusterIssuer
  commonName: namespaces-admission-webhook
  dnsNames:
    - namespaces-admission-webhook
    - namespaces-admission-webhook.${NAMESPACE}
    - namespaces-admission-webhook.${NAMESPACE}.svc
    - namespaces-admission-webhook.${NAMESPACE}.svc.kube-${CLUSTER_IDENTIFIER}.local
