version: "3.6"

services:
  blog:
    build:
      context: .
    image: "blog"
    ports:
      - "8080:5000"
    volumes:
      - ./:/app
    environment:
      FLASK_APP: blog.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
      SECRET_KEY: development
