[tool.poetry]
name = "blog"
version = "0.1.0"
description = ""
authors = ["Tomasz Klosinski <tomasz.klosinski@movedigital.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
